### ISSUE TITLE
Create Python frozen requirements file

### ISSUE THREAD

**Issue by pombredanne** [nexB/dependentcode#8]
We need to create Python frozen requirements file: this may need a specific convention as a requirements file is not your typical lockfile-only format. We likely want to use using pip freeze.

**Comment by pombredanne** [comment]
For info, the lockfile is named requirements.deplock

**Comment by keshav-space** [comment]
As suggested by @pombredanne, use `pip inspect` instead of `pip freeze`. https://github.com/nexB/dependency-inspector/pull/25
> `pip freeze` does not include the relationship between dependencies. Instead, use `pip inspect` to get the JSON report of the Python environment, which includes the dependency relationships, and store it in the `pip-inspect.deplock` file.
